#!/bin/bash
total 12
-rw-r--r-- 1 root root 62 Mar  8 02:58 0-current_working_directory
-rw-r--r-- 1 root root 16 Mar  8 02:18 1-listit
-rw-r--r-- 1 root root  0 Mar  8 03:57 3-listfiles
-rw-r--r-- 1 root root 45 Mar  8 02:11 README.md
